# Generated by Django 5.0.1 on 2024-01-10 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'branch_list',
            },
        ),
        migrations.CreateModel(
            name='FeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.FloatField()),
                ('amount_to', models.FloatField()),
                ('fee', models.FloatField()),
                ('status', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fee_list',
            },
        ),
        migrations.CreateModel(
            name='TransactionInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('sender_first_name', models.CharField(max_length=255)),
                ('sender_last_name', models.CharField(max_length=255)),
                ('sender_middle_name', models.CharField(max_length=255)),
                ('sender_contact', models.CharField(max_length=255)),
                ('sender_address', models.CharField(max_length=255)),
                ('receiver_first_name', models.CharField(max_length=255)),
                ('receiver_last_name', models.CharField(max_length=255)),
                ('receiver_middle_name', models.CharField(max_length=255)),
                ('receiver_contact', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transaction_info',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=255)),
                ('branch_id', models.IntegerField()),
                ('sending_amount', models.FloatField()),
                ('fee', models.FloatField()),
                ('purpose', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('db_status', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_list',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
